In [1]:
import numpy as np
# zero dim (axis) (0D) tensor (scalar)
x = np.array(12)

In [2]:
x

array(12)

In [3]:
x.ndim

0

In [4]:
# One dim (axis) (1D) tensor (vector - itself is 5 dimensional)
y = np.array([12,3,4,5])

In [5]:
y

array([12,  3,  4,  5])

In [6]:
y.ndim

1

In [7]:
y.shape

(4,)

In [8]:
y.dtype

dtype('int64')

In [9]:
yy = np.array([[1,2], [2,4], [3,6], [4,8]])

In [10]:
yy.ndim

2

In [11]:
yy.shape

(4, 2)

In [12]:
# matrix (2D tensor) - array of vectors
z = np.array([
    [5,4,2,5],
    [3,5,7,6],
    [6,12,7,8]
])
# 5,4,2 is the first row and 5,3,6 is the first column

In [13]:
z

array([[ 5,  4,  2,  5],
       [ 3,  5,  7,  6],
       [ 6, 12,  7,  8]])

In [14]:
z.ndim

2

In [15]:
z.shape

(3, 4)

In [16]:
# 3D tensors is higher order array of matrices
xy = np.array([
    [[ 5,  4,  2],
       [ 3,  5,  7],
       [ 6, 12,  7]],
    
    [[ 0,  2,  3],
       [ 34,  52, 2],
       [ 3, 11,  2]],
    
    [[ 31,  4,  88],
       [ 13,  25,  57],
       [ 66, 22,  17]]
    
])

In [17]:
xy

array([[[ 5,  4,  2],
        [ 3,  5,  7],
        [ 6, 12,  7]],

       [[ 0,  2,  3],
        [34, 52,  2],
        [ 3, 11,  2]],

       [[31,  4, 88],
        [13, 25, 57],
        [66, 22, 17]]])

In [18]:
xy.ndim

3

In [19]:
xy.shape

(3, 3, 3)

In [20]:
#Slicing the data
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
my_slice = train_images[10:100] # get slice from 10 to 99 (90 images)
print(my_slice.shape)

(90, 28, 28)


In [21]:
#following is same as above
my_slice = train_images[10:100, : , :]
#is same as 
my_slice = train_images[10:100, 0:28, 0:28]
print(my_slice.shape)

(90, 28, 28)
